clone_depth: 10

version: "{build}"

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

# scripts that are called at very beginning, before repo cloning
# convert LF endings into CRLF when you check out the code
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: "10"
      platform: x86
    - nodejs_version: "11"
      platform: x86
    - nodejs_version: "12"
      platform: x86
    - nodejs_version: "13"
      platform: x86
    - nodejs_version: "14"
      platform: x86


install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - npm -g install grunt-cli

test_script:
  # Output useful info for debugging
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json